### ISSUE TITLE
mysql数据库同步的时候，如果是int类型的值为null，同步会有问题

### ISSUE THREAD

**Issue by polarrwl** [aitinycloud/dbsync#1]
代码中所有类型都是按照字符串处理，如果mysql的table字段是int类型且是空值，则会被转换成string的""空字符，insert的时候传递''给到int类型字段导致错误。
建议：insert增加类型判断，对于int和其他特殊类型进行处理。

**Comment by zhangjinming** [comment]
已收到反馈,欢迎各位提供PR，合并代码。
